###HEALTH
GET http://localhost:3000/health


###Create User
POST http://localhost:3000/user 
Content-Type: application/json

{
    "name":"DEFAULT",
    "email":"default@petshop.com",
    "password":"1234",
    "role": "DEFAULT"
}

###LOGIN
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email":"admin@petshop.com",
    "password":"1234"
}

///////////////////////// USERS

### GetAll
GET http://localhost:3000/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoiZGVmYXVsdEBwZXRzaG9wLmNvbSIsImlhdCI6MTc4MTExMzkzNywiZXhwIjoxNzgxMTE3NTM3fQ.X7-H7SUfScmt6NxVy2P6fFH5AjwgtUD9cGRK92ujujI


//////////////////////// PRODUCTS

### GetAll
GET http://localhost:3000/products
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoiZGVmYXVsdEBwZXRzaG9wLmNvbSIsImlhdCI6MTc4MTExMzkzNywiZXhwIjoxNzgxMTE3NTM3fQ.X7-H7SUfScmt6NxVy2P6fFH5AjwgtUD9cGRK92ujujI


### create
POST http://localhost:3000/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiYWRtaW5AcGV0c2hvcC5jb20iLCJpYXQiOjE3ODExMTQzODgsImV4cCI6MTc4MTExNzk4OH0.CWeTvUyjw8OZp1obSVkOcnFriN-6nKvFtmxc46_R21o
Content-Type: application/json

{
    "label":"label",
    "price":10,
    "description":"description",
    "image":"image",
    "categoria":"categoria",
    "animal":"animal"
}

### delete
DELETE http://localhost:3000/products/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoiZGVmYXVsdEBwZXRzaG9wLmNvbSIsImlhdCI6MTc4MTExMzkzNywiZXhwIjoxNzgxMTE3NTM3fQ.X7-H7SUfScmt6NxVy2P6fFH5AjwgtUD9cGRK92ujujI


### update
PUT http://localhost:3000/products/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoiZGVmYXVsdEBwZXRzaG9wLmNvbSIsImlhdCI6MTc4MTExMzkzNywiZXhwIjoxNzgxMTE3NTM3fQ.X7-H7SUfScmt6NxVy2P6fFH5AjwgtUD9cGRK92ujujI
Content-Type: application/json

{
    "label":"lablel",
    "price":10,
    "description":"description",
    "image":"image",
    "categoria":"categoria",
    "animal":"animal"
}