###HEALTH
GET http://localhost:6767/health


###Create User
POST http://localhost:6767/user 
Content-Type: application/json

{
    "name":"default",
    "email":"default@petshop.com",
    "password":"123",
    "role":"DEFAULT"
}

###LOGIN
POST http://localhost:6767/auth/login
Content-Type: application/json

{
    "email":"admin@petshop.com",
    "password":"123"
}

///////////////////////// USERS ///funcionando

### GetAll
GET http://localhost:6767/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiYWRtaW5AcGV0c2hvcC5jb20iLCJpYXQiOjE3ODEyOTUwNTUsImV4cCI6MTc4MTMwNTg1NX0.kavZYh_XVs3RWMF9T4avwGp0WzF6QEc3xsVcIVh6LfY



//////////////////////// PRODUCTS

### GetAll //ok
GET http://localhost:6767/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiYWRtaW5AcGV0c2hvcC5jb20iLCJpYXQiOjE3ODE4OTQwMDYsImV4cCI6MTc4MTkwNDgwNn0.8LbN8CYntwh2tKOsZg1PLovIslYt1CilbWl-NcOSsqo


### create  // ok
POST http://localhost:6767/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiYWRtaW5AcGV0c2hvcC5jb20iLCJpYXQiOjE3ODEyODY1MTEsImV4cCI6MTc4MTI5NzMxMX0.7lgNlzOVvVHvh6ImLWZq_yUkPFLsK29oqoLzQjHTJ_o
Content-Type: application/json

{
    "label":"label",
    "price":10,
    "description":"description",
    "image":"image",
    "categoria":"categoria",
    "animal":"animal"
}

### delete  //ok
DELETE http://localhost:6767/products/18
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiYWRtaW5AcGV0c2hvcC5jb20iLCJpYXQiOjE3ODE1NDkzNzYsImV4cCI6MTc4MTU2MDE3Nn0.aBrSDjbJ-bdZ7pBQZXYfuFoC8ydQ4cv2KmnOhmxFP0E


### update  //ok
PUT http://localhost:6767/products/15
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiYWRtaW5AcGV0c2hvcC5jb20iLCJpYXQiOjE3ODEyODk2MzMsImV4cCI6MTc4MTMwMDQzM30.syjNgbfBcFWSAI3rdd8Cihn8NCHRXrVGk7DRxV2rJHU
Content-Type: application/json

{
    "label": "dogFood2",
    "description": "Sabor irresistível e alta digestibilidade. Rica em vitaminas essenciais para manter seu cão forte e saudável.",
    "price": 45,
    "image": "dogFood",
    "categoria": "food",
    "animal": "dog"
}
###
